package constant

const (
	// Create ...
	Create = "create_migration"
	// CreateSeed ...
	CreateSeed = "create_seed_file"
	// CreateFromFile ...
	CreateFromFile = "create_migration_from_file"
	// Migrate ...
	Migrate = "migrate"
	// Seed ...
	Seed = "seed"
	// Rollback ...
	Rollback = "rollback"
	// SetDir ...
	SetDir = "set_dir"
	// SetDB ...
	SetDB = "set_db"
)
