package entity

// Config for running gan
type Config struct {
	Dir              string           `json:"dir"`
	Conn             string           `json:"conn"`
	SeedDir          string           `json:"seed_dir"`
	ProjectPackage   string           `json:"project_package"`
	ProjectStructure ProjectStructure `json:"project_structure"`
	CreatorApp       CreatorApp       `json:"creator_app_info"`
}

type CreatorApp struct {
	PackageURL         string `json:"package_url"`
	StarterProjectName string `json:"starter_name"`
	StarterPackageName string `json:"starter_package"`
}

// ProjectStructure of app that will generated by gan
type ProjectStructure struct {
	Entity  Item `json:"entity"`
	Store   Item `json:"repository"`
	UseCase Item `json:"use_case"`
}

// Item of field in project structure
type Item struct {
	Dir      string `json:"dir"`
	Template string `json:"template"`
}
