package constant

const (
	// PathAppName ...
	PathAppName = "src/github.com/zainul/gan"
	// FileTypeMigration ...
	FileTypeMigration = "migration"
	// FileTypeMigrationFromFile ...
	FileTypeMigrationFromFile = "migrationFromFile"
	// FileTypeMigrationUp ...
	FileTypeMigrationUp = "migrationUp"
	// FileTypeCreationSeed ...
	FileTypeCreationSeed = "migrationSeed"
)
